import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { parseModel } from "../src/engine/parser";
import { flatten } from "../src/engine/flattener";
import { resolveEncodings } from "../src/engine/encodingResolver";
import { emit } from "../src/engine/codeEmitter";
import type { EncodedMachine } from "../src/engine/types";

// Slice one function definition out of the emitted .cc (up to its closing
// brace at column 0).
const fn = (cc: string, sig: string) => {
  const at = cc.indexOf(sig);
  return at < 0 ? "" : cc.slice(at, cc.indexOf("\n}", at) + 2);
};

// A model with no CommPattern send_down/send_up pair.
const bareMachine = (): EncodedMachine => ({
  name: "m0",
  chain: ["m0"],
  variables: [],
  variableTypes: new Map(),
  events: [
    { label: "INITIALISATION", parameters: [], guards: [], actions: [] },
    { label: "tick", parameters: [], guards: [], actions: [] },
  ],
  encodings: new Map(),
});

// A model whose event names collide with base-class methods.
const collidingMachine = (): EncodedMachine => ({
  name: "m0",
  chain: ["m0"],
  variables: [],
  variableTypes: new Map(),
  events: [
    { label: "INITIALISATION", parameters: [], guards: [], actions: [] },
    { label: "receive", parameters: [], guards: [], actions: [] },
    { label: "tick", parameters: [], guards: [], actions: [] },
  ],
  encodings: new Map(),
});

const load = (n: string) =>
  ({ name: `${n}.bum`, xml: readFileSync(`tests/fixtures/shdecom/${n}.bum`, "utf8") });
const gen = (target: string, files: string[], name: string) =>
  emit(resolveEncodings(flatten(parseModel(files.map(load)), target)), name);

describe("codeEmitter", () => {
  const tree = gen("pM1", ["pM1"], "Pm1App");
  const file = (ext: string) => tree.find((f) => f.path === `Pm1App.${ext}`)!.content;

  it("emits exactly three files named after the output name", () => {
    expect(tree.map((f) => f.path).sort()).toEqual(["Pm1App.cc", "Pm1App.h", "Pm1App.ned"]);
  });
  it("stamps every file with a provenance banner (source model, no roadmap text)", () => {
    for (const ext of ["h", "cc", "ned"]) {
      expect(file(ext)).toContain("Generated by wsn-codegen from the Event-B machine pM1");
      expect(file(ext)).not.toMatch(/next step/i);
    }
  });
  it("banner names the whole merged chain, not one fixed machine", () => {
    const merged = gen("pM3", ["pM1", "uM2", "pM3"], "WsnApp");
    for (const f of merged) {
      expect(f.content).toContain(
        "Generated by wsn-codegen from the Event-B refinement chain pM1 → uM2 → pM3 (merged into one module)",
      );
    }
  });
  it("declares ENC-typed state fields", () => {
    const h = file("h");
    expect(h).toContain("std::set<std::pair<Node, PktId>> sentUp");
    expect(h).toContain("std::map<PktId, std::set<Node>> ctlNeighbours");
    expect(h).toContain("std::set<PktId> createdPkts");
    expect(h).toContain("std::map<PktId, Node> pktFwdr");
  });
  it("wraps the class in the INET SensorApp shell: ApplicationBase + socket callback", () => {
    const h = file("h");
    expect(h).toContain("class Pm1App : public ApplicationBase, public INetworkSocket::ICallback");
    expect(h).toContain('#include "inet/applications/base/ApplicationBase.h"');
    // INetworkSocket.h uses Protocol without including it; Protocol.h must
    // come first (same include order as SensorApp.h) or the header won't parse.
    expect(h).toMatch(/#include "inet\/common\/Protocol\.h"[\s\S]*#include "inet\/networklayer\/contract\/INetworkSocket\.h"/);
    expect(h).toContain("void handleMessageWhenUp(cMessage *msg) override;");
    expect(h).not.toContain("RoutingProtocolBase");
  });
  it("emits the pattern's send_down as sendSensorPacket, merged with the transmit structure (thesis S4)", () => {
    const cc = file("cc");
    const body = fn(cc, "bool Pm1App::sendSensorPacket");
    expect(body).toContain("if (!(sentDown.count({x, pkt}) > 0))\n        return false;"); // model guard first
    expect(body).toContain("packet->addTag<L3AddressReq>()->setDestAddress(sinkAddress);");
    expect(body).toContain("emit(packetSentSignal, packet);");
    expect(body).toContain("socket->send(packet);");
    // renamed, not duplicated: the Event-B label survives only as provenance
    expect(cc).toContain("Event-B: send_down");
    expect(cc).not.toMatch(/bool Pm1App::send_down/);
    // ⚠ The "no separate void shell fn" claim holds at structure 1 only. The
    // default moved to structure 2 in the 2026-09-13 renumber, and structure 2's
    // parity behaviour is precisely that the sensing timer calls a void
    // `sendSensorPacket()` -- the baseline's own wiring -- alongside this bool
    // overload. Asserted against structure 1 so the claim keeps its meaning.
    const v1cc = emit(resolveEncodings(flatten(parseModel([load("pM1")]), "pM1")), "Pm1App", 1)
      .find((f) => f.path === "Pm1App.cc")!.content;
    expect(v1cc).not.toMatch(/void Pm1App::sendSensorPacket/);
    expect(cc).not.toMatch(/void Pm1App::sendDown\(/);
    expect(cc).not.toMatch(/void Pm1App::sendUp\(/);
  });
  it("emits the pattern's send_up as a socketDataArrived model overload (thesis S5)", () => {
    const cc = file("cc");
    const body = fn(cc, "bool Pm1App::socketDataArrived");
    expect(body).toContain("if (!(sentUp.count({x, pkt}) == 0))\n        return false;"); // model guards kept
    expect(body).toContain("receivedCount++;");
    expect(body).toContain("sentUp.insert({x, pkt});"); // model actions kept
    expect(cc).toContain("Event-B: send_up");
    expect(cc).not.toMatch(/bool Pm1App::send_up/);
  });
  it("the socket-callback socketDataArrived keeps the packet-object mechanics and points at the model overload", () => {
    const cc = file("cc");
    const body = fn(cc, "void Pm1App::socketDataArrived");
    expect(body).toContain("emit(packetReceivedSignal, packet);");
    expect(body).toContain("delete packet;");
    expect(body).toMatch(/socketDataArrived\(x/); // example call in the extension point
  });
  it("timer branch of handleMessageWhenUp points at sendSensorPacket(x, pkt) and reschedules", () => {
    const cc = file("cc");
    const body = fn(cc, "void Pm1App::handleMessageWhenUp");
    expect(body).toMatch(/sendSensorPacket\(x/); // example call in the extension point
    expect(body).toContain("scheduleNextSensing(simTime());");
    expect(body).toContain("socket->processMessage(msg);");
  });
  it("falls back to SensorApp's own sendSensorPacket when a model has no CommPattern pair", () => {
    const cc = emit(bareMachine(), "BareApp").find((f) => f.path === "BareApp.cc")!.content;
    expect(cc).toContain("void BareApp::sendSensorPacket()");
    expect(cc).toContain("socket->send(packet);");
    const recv = fn(cc, "void BareApp::socketDataArrived");
    expect(recv).toContain("receivedCount++;");
  });
  it("implements the lifecycle handlers with SensorApp bodies, not empty stubs", () => {
    const cc = file("cc");
    expect(cc).toMatch(/void Pm1App::handleStartOperation\([^)]*\)\s*\{[^}]*openSocket\(\);/);
    expect(cc).toMatch(/void Pm1App::handleStopOperation\([^)]*\)\s*\{[^}]*cancelNextSensing\(\);/);
    expect(cc).toMatch(/void Pm1App::handleCrashOperation\([^)]*\)\s*\{[^}]*destroy\(\);/);
  });
  it("reads SensorApp parameters in initialize(INITSTAGE_LOCAL)", () => {
    const cc = file("cc");
    expect(cc).toContain("void Pm1App::initialize(int stage)");
    expect(cc).toContain("ApplicationBase::initialize(stage);");
    expect(cc).toContain('timer = new cMessage("sensingTimer");');
  });
  it("marks the identity-binding extension points in the dispatcher and receive callback", () => {
    const cc = file("cc");
    expect(cc).toContain("EXTENSION POINT (send-down flow)");
    expect(cc).toContain("EXTENSION POINT (send-up flow)");
  });
  it("emits a guarded method per event with early-return guards", () => {
    const cc = file("cc");
    expect(cc).toMatch(/bool Pm1App::start_tx\([^)]*\)\s*\{/);
    // guard early-returns break onto their own indented line
    expect(cc).toContain("if (!(sentDown.count({x, pkt}) == 0))\n        return false;");
    expect(cc).toContain("return true;");
  });
  it("renders an action-less non-pattern event as a bool predicate", () => {
    const cc = emit(bareMachine(), "BareApp").find((f) => f.path === "BareApp.cc")!.content;
    expect(cc).toMatch(/bool BareApp::tick\(\)\s*\{\s*return true;\s*\}/);
  });
  it("emits a NED-resolvable module: standalone simple like IApp, class bound via @class", () => {
    const ned = file("ned");
    expect(ned).not.toContain("RoutingProtocolBase");
    expect(ned).toContain("simple Pm1App like IApp");
    expect(ned).toContain("@class(Pm1App)");
    expect(ned).toContain("input socketIn @labels(ITransportPacket/up)");
    expect(ned).toContain("output socketOut @labels(ITransportPacket/down)");
  });
  it("declares the SensorApp parameters and signals in the NED module", () => {
    const ned = file("ned");
    expect(ned).toContain('string sinkAddress = default("")');
    expect(ned).toContain("volatile double sensingInterval @unit(s)");
    expect(ned).toContain("int payloadLength @unit(B)");
    expect(ned).toContain('string networkProtocol = default("")');
    expect(ned).toContain("@signal[packetSent](type=inet::Packet)");
    expect(ned).toContain("@signal[packetReceived](type=inet::Packet)");
  });
});

// The emitted structures, numbered as the paper numbers them (renumbered
// 2026-09-13). 1 = the SensorApp shell with the transmit left behind an
// extension point and the context in shipped fixture headers; 2 = 1 brought to
// behavioural parity, self-contained; 3 = 2's shell carrying PPkt.
//
// ⚠ 3 is indistinguishable from 2 AT THIS LEVEL on purpose: the shell is the
// same and the packet classes are spliced on afterwards by the pipeline, so
// emit() treats 3 as 2. What makes 3 different is covered in generateNet.test.ts.
describe("emit versions (compare-table outputs)", () => {
  const vTree = (v: 1 | 2 | 3) =>
    emit(resolveEncodings(flatten(parseModel([load("pM1")]), "pM1")), "Pm1App", v);
  const vFile = (v: 1 | 2 | 3, ext: string) =>
    vTree(v).find((f) => f.path === `Pm1App.${ext}`)!.content;

  it("1: SensorApp shell, transmit behind the extension point, context in fixtures", () => {
    const h = vFile(1, "h");
    const cc = vFile(1, "cc");
    expect(h).toContain("public ApplicationBase");
    // The context lives in shipped fixture headers, which is why a module
    // downloaded from the web build could not compile — the reason 2 exists.
    expect(h).toContain('#include "eb_context.h"');
    expect(cc).toContain("EXTENSION POINT");
    // The CommPattern pair is already merged and renamed at this structure.
    expect(cc).toContain("bool Pm1App::sendSensorPacket(Node x, PktId pkt)");
    expect(cc).toContain("bool Pm1App::socketDataArrived(");
  });

  it("2: same shell, transmit bound and the context inlined — three self-contained files", () => {
    const h = vFile(2, "h");
    const cc = vFile(2, "cc");
    expect(h).toContain("public ApplicationBase");
    // Self-containment is the whole point of 2: no fixture includes at all.
    expect(h).not.toContain('#include "eb_context.h"');
    expect(h).not.toContain('#include "eb_helpers.h"');
    expect(h).toContain("inline const int");            // context inlined instead
    expect(vTree(2).map((f) => f.path).sort())
      .toEqual(["Pm1App.cc", "Pm1App.h", "Pm1App.ned"]);
    // ⚠ Structure 2 KEEPS both EXTENSION POINT markers -- they are the
    // documented remaining hand step (the identity binding), and structure 3 is
    // what finally replaces them. What 2 adds over 1 is the bound transmit and
    // the inlined context, not the removal of those markers.
    expect(cc).toContain("EXTENSION POINT");
    expect(cc).toContain("void Pm1App::sendSensorPacket()");   // parity: timer-driven
  });

  it("2 is the default, and 3 shares its shell exactly", () => {
    const dflt = emit(resolveEncodings(flatten(parseModel([load("pM1")]), "pM1")), "Pm1App");
    expect(dflt.find((f) => f.path === "Pm1App.h")!.content).toBe(vFile(2, "h"));
    // 3 = 2 at this level; the packet classes are spliced on by the pipeline.
    expect(vFile(3, "h")).toBe(vFile(2, "h"));
  });

  it("all versions break guard early-returns onto their own line", () => {
    for (const v of [1, 2, 3] as const)
      expect(vFile(v, "cc")).toContain("if (!(!nbrs.empty()))\n        return false;");
  });
});

describe("base-class name collisions (structure 2)", () => {
  const h = (v: 1 | 2 | 3) =>
    emit(collidingMachine(), "CollApp", v).find((f) => f.path === "CollApp.h")!.content;

  it("re-exposes a hidden base overload when an event is named like one", () => {
    // `bool receive(...)` would otherwise hide cSimpleModule::receive() and its
    // timeout overload (-Woverloaded-virtual).
    expect(h(2)).toContain("using omnetpp::cSimpleModule::receive;");
    // the Event-B name itself is kept
    expect(h(2)).toContain("bool receive(");
  });

  it("emits no using-declaration for events that collide with nothing", () => {
    expect(h(2)).not.toContain("cSimpleModule::tick");
  });

  it("is a parity-structure feature: 1 does not carry it, 2 and 3 do", () => {
    // The using-declaration arrived with the parity structure (old v4, now 2),
    // so structure 1 -- the frozen pre-parity shell -- must not have it, and 3
    // shares 2's shell so it must.
    expect(h(1)).not.toContain("using omnetpp::cSimpleModule");
    for (const v of [2, 3] as const) expect(h(v)).toContain("using omnetpp::cSimpleModule");
  });
});

// A context may NAME a type and then use the bare name to type both a constant
// and an event parameter -- RTMCS C3 declares `WSN = ND ↔ ND`, `wsnTopology ∈
// WSN`, and `set_link` takes `l ∈ WSN`. Neither the constant emitter nor the
// parameter typer looked through such a name, so `wsnTopology` was emitted
// nowhere and `l` came out `int`: the generated module referenced an undeclared
// identifier and compared an int to it. g++ reported only the undeclared name,
// which made the second half easy to miss.
describe("context-named types", () => {
  const ctx = [{
    name: "C3",
    sets: [],
    constants: ["WSN", "wsnTopology"],
    axioms: [
      { label: "axm3_1", text: "WSN = ND ↔ ND" },
      { label: "axm3_2", text: "wsnTopology ∈ WSN" },
    ],
  }];
  const machine = (): EncodedMachine => ({
    name: "m0", chain: ["m0"], variables: [], variableTypes: new Map(),
    events: [
      { label: "INITIALISATION", parameters: [], guards: [], actions: [] },
      { label: "set_link", parameters: ["l"], guards: ["l ∈ WSN"], actions: [] },
    ],
    encodings: new Map(),
  });
  const out = emit(machine(), "AliasApp", 2, ctx);
  const h = out.find((f) => f.path === "AliasApp.h")!.content;
  const cc = out.find((f) => f.path === "AliasApp.cc")!.content;

  it("declares a constant typed by a named relation as a set of pairs", () => {
    // A relation may map one domain value to several range values, so a
    // std::map cannot hold it -- and a set of pairs is also what gives the
    // emitted `l == wsnTopology` a working operator==.
    expect(h).toContain("inline std::set<std::pair<Node, Node>> wsnTopology;");
  });

  it("types a parameter declared with that name as the same container", () => {
    expect(cc).toContain("bool AliasApp::set_link(const std::set<std::pair<Node, Node>>& l) {");
  });

  it("does not mistake a value equation for a type alias", () => {
    // `CTL_VAL = 0` and `BROADCAST = −1` must keep reaching the scalar path.
    const valueCtx = [{
      name: "C1", sets: [], constants: ["CTL_VAL"],
      axioms: [{ label: "axm1_1", text: "CTL_VAL = 0" }],
    }];
    const vh = emit(machine(), "ValApp", 2, valueCtx).find((f) => f.path === "ValApp.h")!.content;
    expect(vh).toContain("inline const int CTL_VAL = 0;");
  });
});

// A set-typed parameter's element type may itself be a Cartesian product.
// MintRoute M5's report_routeCompletion takes `r ∈ ℙ(ℤ × ℤ)`; reading only the
// first token after ℙ( produced `std::set<Data>` -- a set of scalars where the
// model means a set of pairs.
describe("set-typed parameters over a product", () => {
  const ev = (guard: string) => ({
    name: "m0", chain: ["m0"], variables: [], variableTypes: new Map(),
    events: [
      { label: "INITIALISATION", parameters: [], guards: [], actions: [] },
      { label: "takes_r", parameters: ["r"], guards: [guard], actions: [] },
    ],
    encodings: new Map(),
  }) as EncodedMachine;
  const ccFor = (guard: string) =>
    emit(ev(guard), "ProdApp", 2, []).find((f) => f.path === "ProdApp.cc")!.content;

  it("types a set over a product as a set of pairs", () => {
    expect(ccFor("r ∈ ℙ(ℤ × ℤ)"))
      .toContain("bool ProdApp::takes_r(const std::set<std::pair<Data, Data>>& r) {");
  });

  it("still types a set over a single carrier exactly as before", () => {
    expect(ccFor("r ∈ ℙ(ND)")).toContain("bool ProdApp::takes_r(const std::set<Node>& r) {");
    expect(ccFor("r ∈ ℙ(ℤ)")).toContain("bool ProdApp::takes_r(const std::set<Data>& r) {");
  });
});
